---
extends: default

ignore: |
  docker/kubernetes/helm/**/templates/
  .github/workflows/
  ci-cd/.github/workflows/

rules:
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  braces:
    max-spaces-inside: 1
    level: warning
